/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed. It is
// regenerated by Expo and gives TypeScript the ambient types for the
// Expo SDK (process.env.EXPO_PUBLIC_*, asset imports, etc.).
